// imported libraries
import type { AppProps } from "next/app";
import Head from "next/head";
import dynamic from "next/dynamic";
import { Titillium_Web } from "next/font/google";

// imported Components
const Menu = dynamic(() => import("@/components/navigation/menu/menu"));
const Collapse = dynamic(
  () => import("@/components/navigation/collapse/collapse")
);

// imported styles
import "@/styles/global.scss";

// imported font awesome
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";

// set font awesome
config.autoAddCss = false;

// get inter from google fonts
const ttw = Titillium_Web({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

// create component
export default function App({ Component, pageProps }: AppProps) {
  // return component
  return (
    // create div with inter className
    <div className={ttw.className}>
      {/* add head configuration */}
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>

      {/* add components menu and collapse on mobile */}
      <Menu />
      <Collapse />

      {/* render main component from props with pageProps  */}
      <Component {...pageProps} />
    </div>
  );
}
